name: Build Example

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        goos: [linux, darwin]
    env:
      GOOS: ${{ matrix.goos }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
      - name: Lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.4.0
        env:
          GOOS: ${{ matrix.goos }}
      - name: Vulncheck
        run: |
          GOOS= GOARCH= go install golang.org/x/vuln/cmd/govulncheck@latest
          govulncheck ./...
      - name: Build Example
        run: go build -o /dev/null ./example
      - name: Test
        if: matrix.goos == 'linux'
        run: go test -v ./...
